[tool.poetry]
name = "cdisutils"
version = "0.1.0"
description = ""
authors = ["Justin Barnowski <jbarno@uchicago.edu>"]

[tool.poetry.dependencies]
python = "*"
xmltodict = "0.9.2"
boto = "^2.36"
python-dateutil = "2.4.2"
openpyxl = "^2.5"

[tool.poetry.dev-dependencies]
lockfile = "*"
moto = "0.4.1"
nose = "1.3.7"
mock = "1.3.0"
python-novaclient = "3.2.0"
pytest = "*"
